name: Minecraft PE Servers
description: 
meta_description: "Minecraft PE Servers"

markdown: kramdown
highlighter: rouge

baseurl: '/'

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'http://minecraft-pe-servers.itoytoy.com/'
author:         'iToyToy'

gems: [jekyll-paginate]
